### ISSUE TITLE
Write biography of participants 

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/LDP_raptors_proposal#3]
A list of participants, with affiliations and a short (one paragraph) biographic profile including description of their expertise contributed to the working group. Please distinguish between those who have committed to the project and those who are potential participants.

**Comment by spflaman** [comment]
***NOT UPDATED VERSION***

**Participants** 

We have decided to invite 14 participants to be included in this working group, in the hopes of creating a working group of 12 participants. More can be invited if needed. None of the participants have been contacted yet. See the following descriptions of each participant and how they could contribute to this working group. Note: they are organized in alphabetical order. 

Andrew MacDonald, Postdoctoral Researcher, Université de Sherbrooke  
Research interests: ecology, quantitative ecology, community ecology 
Dr. MacDonald has expertise with Bayesian models which will be beneficial to the working group as this will help create the predictive model that will be looking at raptor response to anthropogenic disturbances.  

Camille Rondeau, MSc Student, Université de Montréal 
Research interests: bird song identification, AI technology 
Camille’s experience with AI identification of bird songs would benefit this working group to allow us to identify different types of raptor calls when conducting fieldwork. 

Carol Frost, Associate Professor/Researcher, University of Alberta 
Research interests: anthropogenic impacts on species 
Dr. Frost’s expertise on how land management affects species’ diversity and interactions would benefit this working group because Dr. Frost could speak about how raptors’ interactions with other predators and prey have been influenced by anthropogenic disturbances and restorations. 

Elder Hazel Dixon, Saskatchewan 
Elder Dixon has partnered with the Royal Saskatchewan Museum, sharing Indigenous stories with the public. Elder Dixon would benefit this working group greatly as she can speak on how raptors have interacted with land in the past and can share her observations on how raptors have been adapting to the disturbed land. 

Gabriel Dansereau, PhD Candidate, Université de Montréal 
Research interests: ecological networks, computational ecology, species distribution modeling 
Gabriel’s expertise in species distribution modeling can help the working group create a model that shows how well raptor species distribute across land that has been restored. 

Juan Andrés Martínez-Lanfranco, PhD Candidate, University of Alberta 
Research interests: ecology and evolution, quantitative ecology 
Juan’s insight into quantitative ecology at the population and community can be incorporated into creating predictive models for raptor responses to anthropogenic restoration. 

Katherine Hébert, PhD Candidate, Université de Sherbrooke 
Research interests: biodiversity change, species interactions  
Katherine’s research on integrating species’ reactions into the assessment for biodiversity will benefit the working group because Katherine will be able to give input on how the biodiversity of raptors changes depending on how they react with other species which can also be impacted by anthropogenic disturbances. 

Kaytlyn Burrows, Operation Burrowing Owl Coordinator, Nature Saskatchewan 
Kaytlyn has held this position since 2013, and she can provide helpful insight into how raptors, such as the burrowing owl, have been influenced by the restoration of the land.  

Megan Lawrence, Director of Salthaven West, Regina SK 
As the director of Salthaven West, Megan has witnessed and helped several raptor species who acquire injury due to anthropogenic modifications to land. Her experience would greatly contribute to the working group as she can share what anthropogenic impacts are injuring raptors. 

Rick Bryne, Saskatchewan Falconry Association, Saskatchewan 
Rick Bryne is the president of the Saskatchewan Falconry Association. Since he is in continual close contact with raptors, he could provide the working group with insight into how raptors interact in different environments, especially environments that have been restored. 

Ryan Fisher, Researcher, Royal Saskatchewan Museum 
Research interests: vertebrate zoology, wildlife management 
Dr. Fisher has worked with different raptors and has experience with wildlife management. This experience would contribute to the working group as Dr. Fisher can share information on how raptors adapt to wildlife management. 

Salix Dubois, MSc Student, Université du Québec à Montréal  
Research interests: ecology, bioinformatics 
Salix’s expertise in bioinformatics will be helpful in creating computer-run programs and models we need to create for this working group. 

Tanya Strydom, PhD Candidate, Université de Montréal 
Research interests: biodiversity, community ecology 
Tanya has expertise in using predictive models for ecological networks and metawebs. This skill would benefit the working group by helping to create the predictive models we want to use to determine how raptors are impacted by the restoration of disturbed land. 

Troy Wellicome, Senior Species At Risk Biologist, Environment and Climate Change Canada and University of Alberta 
Research interests: conservation biology, wildlife ecology, endangered species 
Dr. Wellicome’s expertise would benefit this working group because Dr. Wellicome can contribute his knowledge about raptors that are Species At Risk and what anthropogenic factors are contributing to this.

**Comment by FrancisBanville** [comment]
Francis Banville, PhD Candidate, Université de Montréal
Research interest: ecological networks, food webs, ecological modeling
Francis has expertise in using mathematical models to predict the structure of aquatic and terrestrial food webs.

**Comment by AshSies** [comment]
Ashton Sies, MSc Candidate, University of Regina
Research interests: environmental DNA, bacterial evolution, marine microbial ecology
Ashton has experience and expertise in tidy data formatting and scientific figure production

**Comment by Arenaser** [comment]
Paloma Arena Serrano Ramos, MSc Candidate, Université de Montréal 
Research interests: environment, biological conservation, restoration, marine mammals, biomimetics design, fluid dynamics. 
Arena has experience and expertise in biological conservation and innovation in biomimetic techniques.
